name: Test Hooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm install
        sudo apt-get update
        sudo apt-get install -y jq
    
    - name: Run unit tests
      run: npm test
      continue-on-error: true
    
    - name: Run all tests with verbose output
      run: npm run test:verbose
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          tests/*.log
          ~/.claude/*.log
        if-no-files-found: ignore

  test-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        npm install
        # jq is usually pre-installed on macOS runners
        which jq || brew install jq
    
    - name: Run unit tests
      run: npm test
      continue-on-error: true
    
    - name: Run all tests
      run: npm run test:verbose
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-macos
        path: |
          tests/*.log
          ~/.claude/*.log
        if-no-files-found: ignore

  shellcheck:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run ShellCheck
      run: |
        # Install shellcheck
        sudo apt-get update
        sudo apt-get install -y shellcheck
        
        # Check all shell scripts
        find . -name "*.sh" -type f -print0 | xargs -0 shellcheck -e SC2086,SC2181 || true
        
        echo "✅ All shell scripts checked"